name: Terraform Dev

on:
  push:
    branches: [main]
    paths:
      - 'environments/dev/**'
      - 'modules/**'

jobs:
  terraform-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID:             ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:         ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID:             ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID:       ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_subscription_id:    ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_sql_admin_login:    ${{ secrets.TF_VAR_SQL_ADMIN_LOGIN }}
      TF_VAR_sql_admin_password: ${{ secrets.TF_VAR_SQL_ADMIN_PASSWORD }}
      TF_VAR_enable_sql:         "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.0"

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Format
        working-directory: environments/dev
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan

      - name: Terraform Apply
        working-directory: environments/dev
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
